create-auto-pr:
  name: Create Pull Request from source to target
  runs-on: ubuntu-latest

  # Make sure PR permissions are granted
  permissions:
    contents: write
    pull-requests: write

  steps:
    - name: Create PR using GitHub API (via PAT)
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        SOURCE_BRANCH: ${{ github.event.inputs.source_branch }}
        TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        REPO: ${{ github.repository }}
      run: |
        echo "Creating PR from '$SOURCE_BRANCH' to '$TARGET_BRANCH'..."

        PR_RESPONSE=$(curl -s -X POST https://api.github.com/repos/${REPO}/pulls \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d @- <<EOF
         {
          "title": "PR: Merge '$SOURCE_BRANCH' into '$TARGET_BRANCH'",
          "head": "$SOURCE_BRANCH",
          "base": "$TARGET_BRANCH",
          "body": "This PR was automatically created by GitHub Actions."
         }
EOF
         ) 

         echo "$PR_RESPONSE" | jq

        PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')
        PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

        if [[ "$PR_URL" == "null" ]]; then
          echo "❌ Failed to create PR. Response:"
          echo "$PR_RESPONSE"
          exit 1
        fi

        echo "✅ PR created: $PR_URL"
        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
