name: Daily Scheduled Workflow

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "This is a scheduled job running at 11:30 PM daily"
