name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch (head)'
        required: true
        type: string
      target_branch:
        description: 'Target branch (base)'
        required: true
        type: string
env:       
 GH_TOKEN: ${{ github.token }}
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh pr create \
            --title "Auto PR: ${{ inputs.source_branch }} to ${{ inputs.target_branch }}" \
            --body "This PR was created automatically via GitHub Actions." \
            --head ${{ inputs.source_branch }} \
            --base ${{ inputs.target_branch }} \
            --repo ${{ github.repository }}
