name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch'
        required: true
        default: 'feature-branch'
      target_branch:
        description: 'Target branch'
        required: true
        default: 'main'
      pr_title:
        description: 'Pull request title'
        required: true
        default: 'Automated PR from feature-branch'
      pr_body:
        description: 'Pull request body'
        required: false
        default: 'This PR was created automatically using a workflow.'

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request via GitHub API
        uses: actions/github-script@v7
        with:
          script: |
            const sourceBranch = github.event.inputs.source_branch;
            const targetBranch = github.event.inputs.target_branch;
            const prTitle = github.event.inputs.pr_title;
            const prBody = github.event.inputs.pr_body;

            try {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: prTitle,
                head: sourceBranch,
                base: targetBranch,
                body: prBody
              });
              core.info(`✅ Pull request created: ${pr.html_url}`);
            } catch (error) {
              if (error.status === 422) {
                core.setFailed("❌ A pull request already exists or the source/target branch is invalid.");
              } else {
                core.setFailed(`❌ Unexpected error: ${error.message}`);
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
